
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  commonName: '${common_name}'
  secretName: ${secret_name}
  dnsNames:
  - "${dns_names}"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ${issuer}
    kind: ClusterIssuer
    group: cert-manager.io
